name: adaptx_fixed
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  circular_countdown_timer: ^0.2.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.1
  vibration: ^3.1.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  provider: ^6.1.1
  confetti: ^0.8.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  #firebase_ml_model_downloader: ^0.2.0+8
  #firebase_ml_model_downloader: 0.2.4+1
  firebase_ml_model_downloader: ^0.3.3+5
  package_info_plus: ^8.3.0
  uuid: ^4.3.3
  video_player: ^2.8.1
  chewie: ^1.7.4
  audioplayers: ^6.5.0
  flutter_tts: ^4.2.3
  firebase_database: ^11.3.7
  percent_indicator: ^4.2.3 
  firebase_core: ^3.14.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/videos/
    - assets/videos/Neck_pain/
    - assets/videos/Shoulder_pain/
    - assets/videos/Back_pain/
    - assets/videos/Wrist_pain/
    - assets/videos/Knee_pain/
    - assets/audio/beep.mp3
    - assets/audio/complete.mp3
    - assets/audio/countdown.mp3